### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ricebus** [CRFS/python3-ncplib#13]
Could you add a simple sweep example?

**Comment by etianen** [comment]
You can piece together something from the client docs, here:

http://python3-ncplib.readthedocs.io/en/stable/

However, I will include a complete sweep code example in the docs for the
next release, early next week.

**Comment by etianen** [comment]
And example sweep script can be found here:

https://github.com/CRFS/python3-ncplib/blob/master/examples/sweep.py

This examples directory will be linked to in the docs.

**Comment by etianen** [comment]
It's worth noting here that, while I maintain the Python NCP library, my knowledge of node radio is actually quite limited! I can help you out with usage of the library, as well as general Python help, but other people are better suited for specific Node questions.

If you like, I can pull some of the node team into this conversation, who will be able to help you out more.
